spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:secrets_be/jwt-local.yml
  data:
    redis:
      host: localhost
      port: 6379
