name: BACKEND CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          repository: "PANTS-GOORM/secrets_be"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: "secrets_files"

      - name: Set Secrets YML
        run: |
          mkdir -p src/main/resources
          cp secrets_files/* src/main/resources/secrets_be/

      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Extract version from merge commit message
        run: |
          echo "version=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV

      - name: Print version
        run: echo "Version is $version"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image with version tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pants-rank:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pants-rank:${{ env.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout manifest repository
        uses: actions/checkout@v4
        with:
          repository: "PANTS-GOORM/infra"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: manifest

      - name: Update Deployment image tag
        run: |
          sed -i "s|chickennight/pants-rank:[^[:space:]]*|chickennight/pants-rank:${{ env.version }}|" ./manifest/rank/deployment.yaml
          cd manifest
          git config user.name "chickennight"
          git config user.email "john0513@naver.com"
          git add rank/deployment.yaml
          git commit -m "Update rank image tag to ${{ env.version }}"
          git push
